version: '3'
services:
  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - '8080:8080'
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf

  app:
    container_name: app
    build: .
    ports:
      - '8888:8888'
